version: '3'
services:
  mongodb:
    build: ./wholesaler_db
    environment:
      - MONGODB_USER=root
      - MONGODB_DATABASE=wholesaler
      - MONGODB_PASS=root
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
  wholesaler-server:
    build: ./wholesaler_server
    volumes:
      - ./wholesaler_server/:/wholesaler_server/
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=root
      - MONGODB_DATABASE=wholesaler
      - SPRING_PROFILES_ACTIVE=docker
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 82:8082
  scraper:
    build: ./scraper
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
      - wholesaler-server
    links:
      - wholesaler-server
    ports:
      - 81:8081
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yerbnijse
  web-server:
    build: ./web/server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Europe/Amsterdam
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 80:8080
  web_ui:
    build: ./web/web
    command: bash -c "npm install && npm start"
    links:
      - web-server
    depends_on:
      - web-server
    stdin_open: true
    ports:
      - 84:3000