server:
  port: 8081
logging:
  file:
    name: './logs/server.log'
---
spring:
  config:
    activate:
      on-profile: docker
app:
  testing: false
  warehouse:
    host: http://wholesaler-server:8082
---
spring:
  config:
    activate:
      on-profile: local
app:
  testing: false
  warehouse:
    host: http://localhost:8082