version: '3'
services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yerbnijse
  server:
    build: ./server
    volumes:
      - ./server/:/server/
    environment:
      - SPRING_PROFILES_ACTIVE=local-docker
      - TZ=Europe/Amsterdam

    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 81:8080

  web:
    build: ./web
    volumes:
      - ./web/:/web/
    command: bash -c "npm install && npm start"
    links:
      - server
    depends_on:
      - server
    stdin_open: true
    ports:
      - 82:3000
